#!/bin/bash -e

SOURCE_DIR=$PWD
${SOURCE_DIR}/base/deploy $@

source ${SOURCE_DIR}/config

if [ -f ${CURRENT_DIR}/Gemfile ]; then
	pushd $CURRENT_DIR && bundle install --deployment --without=test development
	popd
fi
