#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /etc/circus
cp ${SOURCE_DIR}/cordova/etc/circus.ini /etc/circus/circus.ini

mkdir /home/application
useradd -s /bin/bash -m ${USER}
chown ${USER}:${USER} /home/application
echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
cp ${SOURCE_DIR}/cordova/etc/nginx.conf /etc/nginx/nginx.conf
