#!/bin/bash -e

su ubuntu -c 'mkdir -p /home/ubuntu/.ssh'
su ubuntu -c 'chmod 700 /home/ubuntu/.ssh'
echo "$@" >> /home/ubuntu/.ssh/authorized_keys
su ubuntu -c 'chown -R ubuntu:ubuntu /home/ubuntu/.ssh'
