#!/bin/bash

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

APP_DIR=/home/application
CURRENT_DIR=${APP_DIR}/current
HOME=/home/ubuntu
USER=ubuntu
VENV_DIR=${APP_DIR}/.circus_env

function echo_debug() {
	if [ ! -z "${TSURU_DEBUG}" ]; then
		echo "$@"
	fi
}
