#!/bin/bash

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

APP_DIR=/home/application
CURRENT_DIR=${APP_DIR}/current
USER=ubuntu
HOME=/home/${USER}

function get_ppa_key() {
	user=$(echo $1 | awk -F / '{print $1}')
	repo=$(echo $1 | awk -F / '{print $2}')
	api_url="https://launchpad.net/~${user}/+archive/ubuntu/${repo}"
	fingerprint=$(curl "${api_url}" | jq -r ".signing_key_fingerprint")
	sudo -E apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv ${fingerprint}
}

function add_repository() {
	ppa=$(echo $1 | grep "^ppa:\(.*\)$")
	if [ "${ppa}" = "${1}" ]; then
		ppa=$(echo $1 | awk -F : '{print $2}')
		repository="deb http://ppa.launchpad.net/${ppa}/ubuntu $(lsb_release -cs) main"
		get_ppa_key $ppa
	else
		repository=$1
	fi
	filename=$(echo $repository | shasum | awk '{print $1}')
	filename="tsuru_${filename}"
	echo "$repository" | sudo -E tee >/dev/null 2>&1 /etc/apt/sources.list.d/${filename}
}

function echo_debug() {
	if [ ! -z "${TSURU_DEBUG}" ]; then
		echo "$@"
	fi
}
