#!/bin/bash

APP_DIR=/home/application
CURRENT_DIR=${APP_DIR}/current
HOME=/home/ubuntu
USER=ubuntu
VENV_DIR=${APP_DIR}/.circus_env

function echo_debug() {
	if [ ! -z "${TSURU_DEBUG}" ]; then
		echo "$@"
	fi
}
