# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

from ubuntu:14.04
add . /var/lib/tsuru
run cp -r /var/lib/tsuru/base/* /var/lib/tsuru
run cp -r /var/lib/tsuru/{{IMAGE_NAME}}/* /var/lib/tsuru
run /var/lib/tsuru/install
