#!/bin/bash -el

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

function so_dependencies() {
    if [ -f ${CURRENT_DIR}/repositories.apt ]; then
        source /var/lib/tsuru/config
        for repo in `cat ${CURRENT_DIR}/repositories.apt`; do
            add_repository ${repo}
        done
    fi
    if [ -f ${CURRENT_DIR}/requirements.apt ]; then
        set +e
        sudo -E apt-get install $(cat ${CURRENT_DIR}/requirements.apt) -y --force-yes
        status=$?
        set -e
        if [ ${status} != 0 ]; then
            sudo apt-get update
            sudo -E apt-get install $(cat ${CURRENT_DIR}/requirements.apt) -y --force-yes
        fi
    fi
}
