#!/bin/sh -el

source config

function so_dependencies() {
    if [ -f ${CURRENT_DIR}/requirements.apt ]; then
        sudo -E apt-get install $(cat ${CURRENT_DIR}/requirements.apt) -y
    else
        echo "requirements.apt not found."
        echo "Skipping..."
    fi
}
