#!/bin/bash
SOURCE_DIR=/var/lib/tsuru
${SOURCE_DIR}/base/deploy $@
shift; shift
export $@
echo "BUILDPACK: $BUILDPACK_URL"

source ${SOURCE_DIR}/config

cd $CURRENT_DIR
sudo /bin/sh -c "rm -rf /app && mkdir /app && cp -a . /app"
sudo -E /build/builder
sudo chown -R ubuntu:ubuntu /app
echo "export PORT=8888" | sudo tee /app/.profile.d/tsuru.sh
LC_ALL=C perl -lne '/^(.*?):/ && print "$1: /start $1"' /app/Procfile | sudo tee /Procfile
sudo sed -i "s/\(\s*\)\(.*\) | bash/\1exec \`\2\`/g" /start
python ${SOURCE_DIR}/hooks.py
