#!/bin/bash
SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
echo "BUILDPACK: $BUILDPACK_URL"

source ${SOURCE_DIR}/config

cd $CURRENT_DIR
sudo /bin/sh -c "rm -rf /app && mkdir /app && cp -a . /app"
sudo -E /build/builder
sudo chown -R ubuntu:ubuntu /app
echo "export PORT=8888" | sudo tee /app/.profile.d/tsuru.sh >/dev/null
LC_ALL=C perl -lne '/^(.*?):/ && print "$1: /start $1"' /app/Procfile | sudo tee /Procfile >/dev/null
sudo sed -i "s^\(\s*\)\(.*\) | bash^\1exec /bin/bash -c \"\`\2\`\"^g" /start
/home/application/.venv/bin/python ${SOURCE_DIR}/hooks.py
