#!/bin/bash -l

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

source /var/lib/tsuru/config

unset PYTHONHOME

circus_params="--log-output /var/log/circus/circus.log"
if [[ $(ps aux | grep -i sshd | grep -v grep) > 0 ]]; then
    circus_params="--daemon $circus_params"
fi

exec ${VENV_DIR}/bin/circusd /etc/circus/circus.ini $circus_params
