#!/bin/bash -el

function so_dependencies() {
    export DEBIAN_FRONTEND=noninteractive
    if [ -f ${CURRENT_DIR}/repositories.apt ]; then
        set +e
        apt-get install software-properties-common -y --force-yes
        status=$?
        set -e
        if [ ${status} != 0 ]; then
            apt-get update
            apt-get install software-properties-common -y --force-yes
        fi
        for repo in `cat ${CURRENT_DIR}/repositories.apt`; do
            add-apt-repository -y ${repo}
        done
    fi
    if [ -f ${CURRENT_DIR}/requirements.apt ]; then
        set +e
        apt-get install $(cat ${CURRENT_DIR}/requirements.apt) -y --force-yes
        status=$?
        set -e
        if [ ${status} != 0 ]; then
            apt-get update
            apt-get install $(cat ${CURRENT_DIR}/requirements.apt) -y --force-yes
        fi
    fi
}
