#!/bin/bash -e

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/config

if [ -f ${CURRENT_DIR}/Gemfile ]; then
	pushd $CURRENT_DIR && sudo bundle install --deployment --without ${BUNDLE_WITHOUT-development:test}
	popd
fi

${VENV_DIR}/bin/python ${SOURCE_DIR}/hooks.py
