#!/bin/bash -e

SOURCE_DIR=/var/lib/tsuru
$SOURCE_DIR/base/install

wget -O - http://prdownloads.sourceforge.net/sbcl/sbcl-1.1.14-x86-64-linux-binary.tar.bz2 2> /dev/null | bzip2 -cd | tar xvf -
cd sbcl-1.1.14-x86-64-linux
sudo sh ./install.sh
cd
rm -rf ./sbcl-1.1.14-x86-64-linux
