#!/bin/bash -l

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

source /var/lib/tsuru/config

TSURU_JAVA_VERSION=${JAVA_VERSION-7}
case $TSURU_JAVA_VERSION in
7)
	java_to_use="java-7-oracle"
	;;
8)
	java_to_use="java-8-oracle"
	;;
*)
	echo "WARNING: invalid Java version, please use \"7\" or \"8\". Using Java 7 as fallback."
	java_to_use="java-7-oracle"
	;;
esac

sudo update-java-alternatives -s $java_to_use > /dev/null
sed -i "s;export JAVA_HOME.*;export JAVA_HOME=/usr/lib/jvm/$java_to_use;" /home/ubuntu/.profile
sed -i "s;#JAVA_HOME#;export JAVA_HOME=/usr/lib/jvm/$java_to_use;" /home/ubuntu/.profile

mkdir -p /home/ubuntu/.ssh
chmod 700 /home/ubuntu/.ssh
echo "JAVA_HOME=/usr/lib/jvm/$java_to_use" > /home/ubuntu/.ssh/environment

/var/lib/tsuru/base/start
