#!/bin/bash -l

source /var/lib/tsuru/config

TSURU_JAVA_VERSION=${JAVA_VERSION-7}
case $TSURU_JAVA_VERSION in
7)
	java_to_use="java-7-oracle"
	;;
8)
	java_to_use="java-8-oracle"
	;;
*)
	echo "WARNING: invalid Java version, please use \"7\" or \"8\". Using Java 7 as fallback."
	java_to_use="java-7-oracle"
	;;
esac

sudo update-java-alternatives -s $java_to_use > /dev/null
/var/lib/tsuru/base/start
