#!/bin/bash

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

source /var/lib/tsuru/base/deploy

echo "Building..."
cd /home/application/current
dir /var/lib/activator --recursive
/var/lib/activator/activator stage

echo "Procfile:"
cat /home/application/current/Procfile
