#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

rm /etc/apache2/sites-enabled/*
ln -s ${SOURCE_DIR}/hhvm/etc/apache-vhost /etc/apache2/sites-enabled/tsuru-vhost.conf
/usr/share/hhvm/install_fastcgi.sh

cat >> /etc/profile<<END
export APACHE_RUN_USER=ubuntu
export APACHE_RUN_GROUP=ubuntu
export APACHE_PID_FILE=/var/run/apache2/apache2.pid
export APACHE_RUN_DIR=/var/run/apache2
export APACHE_LOCK_DIR=/var/lock/apache2
export APACHE_LOG_DIR=/var/log/apache2
END

locale-gen en_US.UTF-8
update-locale