#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /etc/circus
cp ${SOURCE_DIR}/cordova/etc/circus.ini /etc/circus/circus.ini

cp ${SOURCE_DIR}/hhvm/etc/nginx.conf /etc/nginx/nginx.conf

/usr/share/hhvm/install_fastcgi.sh

mkdir -p /var/lib/php5
chown ubuntu:ubuntu /var/lib/php5

sed -i -e 's/80 /8888 /' /etc/nginx/sites-enabled/default
sed -i -e 's/\/usr\/share\/nginx\/html/\/home\/application\/current/' /etc/nginx/sites-enabled/default
sed -i -e 's/index index.html index.htm;/index index.html index.htm index.php;/' /etc/nginx/sites-enabled/default

locale-gen en_US.UTF-8
update-locale