#!/bin/bash -l

source /var/lib/tsuru/config

/usr/sbin/nginx -c /etc/nginx/nginx.conf &

/usr/bin/hhvm --config /etc/hhvm/php.ini --config /etc/hhvm/server.ini --user www-data --mode daemon -vPidFile=/var/run/hhvm/pid &

/var/lib/tsuru/base/start
