#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/config

if [ -f ${CURRENT_DIR}/requirements.txt ]; then
    sudo pip3 install -r ${CURRENT_DIR}/requirements.txt
fi

python2.7 ${SOURCE_DIR}/hooks.py
