#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
${SOURCE_DIR}/base/deploy $@

source ${SOURCE_DIR}/config

GOROOT=${APP_DIR}/go
GOPATH=${APP_DIR}/.go
PATH=${GOROOT}/bin:${GOPATH}/bin:${PATH}
export GOPATH GOROOT PATH

cd ${CURRENT_DIR} && go get -d ./...

shift; shift
export $@
python ${SOURCE_DIR}/hooks.py
