#!/bin/bash -el

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/config

pushd ${CURRENT_DIR} > /dev/null 2>&1

# do not fail if the application is not go gettable
set +e
go get -d ./...
set -e

if [ -f ${APP_DIR}/.default_procfile ]
then
	go build -o tsuru-app
fi

popd
