#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/config

GOPATH=${APP_DIR}
PATH=${GOPATH}/bin:${PATH}
export GOPATH PATH

pushd ${CURRENT_DIR}
go get -d ./...
${VENV_DIR}/bin/python ${SOURCE_DIR}/hooks.py

if [ -f ${APP_DIR}/.default_procfile ]
then
	go build -o tsuru-app
fi

popd
