#!/bin/bash -e

echo "127.0.0.1	`hostname`" | sudo tee -a /etc/hosts
echo "::1	`hostname`" | sudo tee -a /etc/hosts

SOURCE_DIR=/var/lib/tsuru
source $SOURCE_DIR/config

GOROOT=${APP_DIR}/go
GOPATH=${APP_DIR}/.go
PATH=${GOROOT}/bin:${GOPATH}/bin:${PATH}
export PATH GOPATH GOROOT

ENV_FILE=${APP_DIR}/apprc
[ -f ${ENV_FILE} ] && source ${ENV_FILE}

if [ -d ${CURRENT_DIR} ]; then
	cd ${CURRENT_DIR}
	go build -o tsuru-app
	./tsuru-app &
fi
