#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
${VENV_DIR}/bin/python ${SOURCE_DIR}/hooks.py
APP_DIR=/home/application/current
test -e ${APP_DIR}/nginx.conf && sudo cp ${APP_DIR}/nginx.conf /etc/nginx/nginx.conf
