#!/bin/bash -e

echo "export DEBIAN_FRONTEND=noninteractive" >> /etc/profile
apt-get update
apt-get install git python openssh-server gcc make curl libpcre3-dev zlib1g-dev nginx -y
mkdir -p /var/run/sshd
