#!/bin/bash -e

SOURCE_DIR=/var/lib/tsuru
$SOURCE_DIR/base/install
apt-get install gcc make curl libpcre3-dev zlib1g-dev nginx -y
rm -rf /var/log/nginx /var/lib/nginx
mkdir -p /var/log/nginx /var/lib/nginx
chown -R ubuntu:ubuntu /var/lib/nginx /var/log/nginx
cp ${SOURCE_DIR}/static/Procfile ${SOURCE_DIR}/utils/Procfile
cp ${SOURCE_DIR}/static/etc/nginx.conf /etc/nginx/nginx.conf
