#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir /home/application
useradd -m ${USER}
chown ${USER}:${USER} /home/application
echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
useradd nginx
cp ${SOURCE_DIR}/static/etc/nginx.conf /opt/conf/nginx.conf
