#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /etc/circus
cp ${SOURCE_DIR}/static/etc/circus.ini /etc/circus/circus.ini

mkdir -p /home/application

# If the user doesn't exist add it
if [ "$(getent passwd ${USER})" == '' ]; then
	useradd -s /bin/bash -m ${USER};
fi

chown ${USER}:${USER} /home/application
echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
cp ${SOURCE_DIR}/static/etc/nginx.conf /etc/nginx/nginx.conf
