#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
echo "*** $0: \${SOURCE_DIR} = \"${SOURCE_DIR}\""
source ${SOURCE_DIR}/base/deploy

source ${SOURCE_DIR}/config

(
	cd ${CURRENT_DIR}

	echo "*** $0: About to do pip install (pwd: $(pwd))"

	if [ -f ${CURRENT_DIR}/requirements.txt ]; then
		sudo pip install -r ${CURRENT_DIR}/requirements.txt
	elif [ -f ${CURRENT_DIR}/setup.py ]; then
		sudo pip install ${CURRENT_DIR}/
	fi
)

echo "*** $0: Running any hooks in ${SOURCE_DIR}/hooks.py (pwd: $(pwd))"
${VENV_DIR}/bin/python ${SOURCE_DIR}/hooks.py
echo "*** $0: Done."
