#!/bin/bash -e

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/config

if [ -f ${CURRENT_DIR}/package.json ]; then
	pushd $CURRENT_DIR && npm install
	popd
fi

python ${SOURCE_DIR}/hooks.py
