#!/bin/bash -e

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy
source ${SOURCE_DIR}/config

if [ -f ${CURRENT_DIR}/package.json ]; then
	if [ -d ${CURRENT_DIR}/node_modules ]; then rm -rf ${CURRENT_DIR}/node_modules ; fi
	pushd $CURRENT_DIR && npm install --production --cache modules_cache --no-registry --nodedir=/usr/include/nodejs
	popd
fi

python ${SOURCE_DIR}/hooks.py
