#!/bin/bash -le

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

git clone https://github.com/creationix/nvm.git /etc/nvm
cd /etc/nvm && git checkout `git describe --abbrev=0 --tags`

cat >> /home/ubuntu/.profile <<EOF
if [ -e /home/ubuntu/.nvm_bin ]; then
	export PATH="/home/ubuntu/.nvm_bin:$PATH"
fi
EOF
