#!/bin/bash -el

if [ $# -lt 2 ]
then
    echo "Usage:"
    echo
    echo "  % $0 <git-repository> <git-ref-id> <envs>"
    exit 1
fi

function deploy() {
    if [ -d $CURRENT_DIR ]; then
        cd $CURRENT_DIR
        git reset --hard
        git fetch origin
        cd -
    else
        git clone $1 $CURRENT_DIR
    fi
    cd $CURRENT_DIR
    git checkout $2 >/dev/null 2>&1
    cd -
}

SOURCE_DIR=/var/lib/tsuru

# Link shared folders
sudo -E python ${SOURCE_DIR}/sharedfs.py

cat <<"END" | sudo tee -a /etc/profile.d/tsuru.sh >/dev/null
export DEBIAN_FRONTEND=noninteractive
END
source /etc/profile.d/tsuru.sh

source ${SOURCE_DIR}/config
source ${SOURCE_DIR}/so_dependencies
deploy $@
so_dependencies

APP_SIZE=$(du -sh ${CURRENT_DIR} | awk '{print $1}');
echo "Repository size is ${APP_SIZE}"
