#!/bin/bash -el

# do not remove, circus is needed to manage application processes
# and its environment variables
apt-get update
apt-get install -y git-core python-pip libzmq-dev libevent python-virtualenv
pip install git+https://github.com/andrewsmedina/circus.git@validate_option_hooks
#apt-get install git-core openssh-server python-pip libzmq-dev g++ python-dev -y
#pip install git+https://github.com/andrewsmedina/circus.git@validate_option_hooks
pip install tsuru-circus
mkdir /var/run/sshd
echo "export DEBIAN_FRONTEND=noninteractive" >> /etc/profile
apt-get remove --purge -y libzmq-dev g++ python-dev build-essential make
