#!/bin/bash -el

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

chmod +s /usr/bin/sudo

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /home/application
useradd -m ${USER} -s /bin/bash
chown ${USER}:${USER} /home/application
echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:tsuru/ppa
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install curl git wget -y
apt-get install deploy-agent -y --force-yes

mkdir -p ${SOURCE_DIR}/utils

echo "export DEBIAN_FRONTEND=noninteractive" >> /etc/profile
