#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /etc/circus
mv ${SOURCE_DIR}/circus.ini /etc/circus/circus.ini
mkdir /home/application
useradd -m ${USER} -s /bin/bash
chown ${USER}:${USER} /home/application
echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
