#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /etc/circus
cp ${SOURCE_DIR}/utils/circus.ini /etc/circus/circus.ini
mkdir /home/application
useradd -m ${USER}
chown ${USER}:${USER} /home/application
