#!/bin/bash -l

echo '' > /var/lib/tsuru/php/etc/fpm-envs.conf

# Export all environment variables
for var in `env | cut -f1 -d=`; do
	echo "env[$var] = ${!var}" >> /var/lib/tsuru/php/etc/fpm-envs.conf;
done

# Export envs wrote in apprc
grep '^export ' /home/application/apprc | sed -e '0,/RE/s/export /ENV[/' | sed -e '0,/RE/s/=/]=/' >> /var/lib/tsuru/php/etc/fpm-envs.conf
