#!/bin/bash -l

FILENAME=/home/application/fpm-envs.conf

echo '' > ${FILENAME}
chown ubuntu:ubuntu ${FILENAME}

# Export all environment variables
for var in `env | cut -f1 -d=`; do
    if [ "${var}" == 'SUDO_*' ]; then
        continue;
    fi
	echo "env[$var] = \$${var}" >> ${FILENAME};
done

# Export envs wrote in apprc
grep '^export ' /home/application/apprc | sed -e '0,/RE/s/export /env[/' | sed -e '0,/RE/s/=/]=/' >> ${FILENAME}
