#!/bin/bash -el

echo "Deploying the PHP application..."

APP_DIR=/home/application/current
SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy

# Deploying
echo "Starting application configuration"
sudo ${VENV_DIR}/bin/python ${SOURCE_DIR}/php/deploy.py install
${VENV_DIR}/bin/python ${SOURCE_DIR}/php/deploy.py environment

# Run tsuru hooks after
${VENV_DIR}/bin/python ${SOURCE_DIR}/hooks.py
