#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
${SOURCE_DIR}/base/deploy $@

shift; shift
export $@

echo ""
echo "========================================"
echo " Parsing Hooks..."
echo "========================================"
echo ""
python ${SOURCE_DIR}/hooks.py

echo ""
echo "========================================"
echo " Parsing Apache modules to install..."
echo "========================================"
echo ""
sudo python ${SOURCE_DIR}/php/apache_modules.py
