#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /etc/circus
cp ${SOURCE_DIR}/php/etc/circus.ini /etc/circus/circus.ini
mkdir /home/application
useradd -m ${USER} -s /bin/bash
chown ${USER}:${USER} /home/application
echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
rm /etc/apache2/sites-enabled/*
ln -s ${SOURCE_DIR}/php/etc/apache-vhost /etc/apache2/sites-enabled/
cat >> /etc/profile <<END
export APACHE_RUN_USER=ubuntu
export APACHE_RUN_GROUP=ubuntu
export APACHE_PID_FILE=/var/run/apache2/apache2.pid
export APACHE_RUN_DIR=/var/run/apache2
export APACHE_LOCK_DIR=/var/lock/apache2
export APACHE_LOG_DIR=/var/log/apache2
END

# Enabling modules needed by FastCGI
sh /etc/profile
/usr/sbin/a2enmod actions

# Disable PHP5-FPM startup job. We use circusd for that
sudo /usr/sbin/update-rc.d php5-fpm disable
rm /etc/php5/fpm/php-fpm.conf
ln -s ${SOURCE_DIR}/php/etc/php-fpm.conf /etc/php5/fpm/php-fpm.conf
