#!/bin/bash -el

FPM_CONF=/etc/php5/fpm/php-fpm.conf
FPM_POOL_DIR=/etc/php5/fpm/pool.d
SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /etc/circus
cp ${SOURCE_DIR}/php/etc/circus.ini /etc/circus/circus.ini
mkdir /home/application
useradd -m ${USER} -s /bin/bash
chown ${USER}:${USER} /home/application
echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
rm /etc/apache2/sites-enabled/*
ln -s ${SOURCE_DIR}/php/etc/apache-vhost /etc/apache2/sites-enabled/
cat >> /etc/profile <<END
export APACHE_RUN_USER=ubuntu
export APACHE_RUN_GROUP=ubuntu
export APACHE_PID_FILE=/var/run/apache2/apache2.pid
export APACHE_RUN_DIR=/var/run/apache2
export APACHE_LOCK_DIR=/var/lock/apache2
export APACHE_LOG_DIR=/var/log/apache2
END

# Change permissions to fastcgi
chown ${USER}:${USER} -R /var/lib/apache2/fastcgi/

# Enabling modules needed by FastCGI
/usr/sbin/a2enmod actions

# Disable PHP5-FPM startup job. We use circusd for that
sudo /usr/sbin/update-rc.d php5-fpm disable
rm ${FPM_CONF}
ln -s ${SOURCE_DIR}/php/etc/php-fpm.conf ${FPM_CONF}

# Change default FPM Pool
rm ${FPM_POOL_DIR}/www.conf
ln -s ${SOURCE_DIR}/php/etc/tsuru-fpm-pool.conf ${FPM_POOL_DIR}/tsuru.conf

# Environments file for PHP-FPM
touch ${SOURCE_DIR}/php/etc/fpm-envs.conf
