#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /etc/circus
cp ${SOURCE_DIR}/php/etc/circus.ini /etc/circus/circus.ini
mkdir /home/application
useradd -m ${USER} -s /bin/bash
chown ${USER}:${USER} /home/application
echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
rm /etc/apache2/sites-enabled/*
ln -s ${SOURCE_DIR}/php/etc/apache-vhost /etc/apache2/sites-enabled/
