#!/bin/bash -l

# Copyright 2015 basebuilder authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

echo "Starting the PHP application..."

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

# Setup environment variables before starting up
${VENV_DIR}/bin/python ${SOURCE_DIR}/php/deploy.py environment

# Call the default start script
source ${SOURCE_DIR}/base/start
